controller_manager: # Node name
  ros__parameters:
    update_rate: 30 

    robot_base_controller:
      type: diff_drive_controller/DiffDriveController

    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

robot_base_controller:
  ros__parameters:

    publish_rate: 50.0 

    odom_frame_id: odom
    base_frame_id: base_footprint

    left_wheel_names: ['front_left_wheel', 'rear_left_wheel']
    right_wheel_names: ['front_right_wheel', 'rear_right_wheel']

    wheels_per_side: 2 # 1
    wheel_separation: 0.498
    # wheel_separation: 2.0
    wheel_radius: 0.165

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0] 

    enable_odom_tf: true
    cmd_vel_timeout: 0.25 # seconds
    use_stamped_vel: false

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true 
    linear.x.has_jerk_limits: true
    linear.x.max_velocity: 1.0 # m/s
    linear.x.min_velocity: -0.5 # m/s
    linear.x.max_acceleration: 0.8 # m/s^2
    linear.x.min_acceleration: -0.4 # m/s^2
    linear.x.max_jerk: 5.0 # m/s^3

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: true
    angular.z.max_velocity: 1.7 # rad/s
    angular.z.max_acceleration: 1.5 # rad/s^2
    angular.z.max_jerk: 2.5 # rad/s^3
